services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag_api
    shm_size: '2gb'
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - CHROMA_HOST=chromadb
      - PYTHONFAULTHANDLER=1
    depends_on:
      chromadb:
        condition: service_healthy 
    restart: on-failure

  chromadb:
    image: chromadb/chroma:0.5.3
    container_name: rag_chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:


